/*
 * Fail the build on a malformed PostHog key rather than ship one that silently
 * never records. The key is case-sensitive and checked only by PostHog, so
 * what can be caught here is corruption: whitespace or a stray 
 from a
 * Windows line ending, quotes pasted in with it, truncation, or a phx_
 * personal key (read/write access to the account) put where the public
 * project key belongs. An absent key is fine — analytics simply stay off.
 */
const posthogKey = process.env.NEXT_PUBLIC_POSTHOG_KEY;
if (posthogKey !== undefined && posthogKey !== "") {
  if (posthogKey.startsWith("phx_")) {
    throw new Error(
      "NEXT_PUBLIC_POSTHOG_KEY is a PostHog *personal* API key (phx_). That key " +
        "can read and modify your PostHog data and must never ship to the " +
        "browser. Use the project API key (phc_) from Project settings."
    );
  }
  if (!/^phc_[A-Za-z0-9]{40,}$/.test(posthogKey)) {
    throw new Error(
      `NEXT_PUBLIC_POSTHOG_KEY is malformed (length ${posthogKey.length}): ` +
        "expected phc_ followed only by letters and digits, with no spaces, " +
        "quotes or line-ending characters."
    );
  }
}

/*
 * Old article URLs keep working. A post whose slug changed after it went live
 * lists its former slugs in `redirectFrom`; each becomes a 301 in
 * public/_redirects, which Cloudflare Pages applies before serving anything.
 * Written here, rather than in a build script, so it runs on every
 * `next build` whatever the build command is. Generated, so it's gitignored.
 */
const fs = require("node:fs");
const path = require("node:path");

function writeRedirects() {
  const dir = path.join(__dirname, "content", "writing");
  const out = path.join(__dirname, "public", "_redirects");
  const rules = [];
  if (fs.existsSync(dir)) {
    for (const file of fs.readdirSync(dir).filter((f) => f.endsWith(".md"))) {
      const text = fs.readFileSync(path.join(dir, file), "utf8");
      const field = (key, fallback) => {
        const match = new RegExp(`^${key}: (.*)$`, "m").exec(text);
        return match ? JSON.parse(match[1]) : fallback;
      };
      const slug = field("slug", "");
      for (const old of field("redirectFrom", [])) {
        if (old && old !== slug) rules.push(`/writing/${old} /writing/${slug} 301`);
      }
    }
  }
  if (rules.length) {
    const header = "# Generated by next.config.js from content/writing. Don't edit.";
    fs.writeFileSync(out, [header, ...rules, ""].join("\n"));
  } else if (fs.existsSync(out)) {
    fs.rmSync(out);
  }
}
writeRedirects();

/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "export",
  images: {
    // `output: "export"` has no image server, so next/image must not try to
    // optimize on request. Without this, adding next/image breaks the build.
    unoptimized: true,
  },
};

module.exports = nextConfig;
