#!/usr/bin/env node
/*
 * Internal link checker for the static export.
 *
 *   node scripts/check-links.mjs            # checks out/ (run after `next build`)
 *   node scripts/check-links.mjs out --content   # also checks links in content/*.md
 *
 * Every same-site href/src in every built page (and, with --content, every
 * root-relative link in the Markdown sources) must resolve the way Cloudflare
 * Pages resolves it: the file itself, <path>.html, <path>/index.html, or a
 * 301 in out/_redirects. A #fragment must match an id on the target page.
 * Exits 1 when anything is broken, so it can gate a build.
 */
import fs from "node:fs";
import path from "node:path";

const args = process.argv.slice(2);
const root = path.resolve(args.find((a) => !a.startsWith("--")) ?? "out");
const withContent = args.includes("--content");
const ORIGIN = "https://nazarene.dev";

if (!fs.existsSync(root)) {
  console.error(`No ${root}. Run \`npx next build\` first.`);
  process.exit(2);
}

const walk = (dir) =>
  fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    return e.isDirectory() ? walk(p) : [p];
  });

const files = walk(root);
const fileSet = new Set(files.map((f) => path.relative(root, f).split(path.sep).join("/")));

// Cloudflare Pages redirects (generated by next.config.js from redirectFrom).
const redirects = new Map();
const redirectsFile = path.join(root, "_redirects");
if (fs.existsSync(redirectsFile)) {
  for (const line of fs.readFileSync(redirectsFile, "utf8").split("\n")) {
    const [from, to] = line.trim().split(/\s+/);
    if (from && to && !from.startsWith("#")) redirects.set(from, to);
  }
}

// Paths served by Pages Functions rather than files (functions/), and /admin,
// which Cloudflare Access fronts. Links to these are not checked as files.
const DYNAMIC = [/^\/api\//, /^\/ingest\//, /^\/media\//, /^\/cdn-cgi\//];

/** The built file a URL path is served from, or null. */
function resolve(urlPath, hops = 0) {
  let p = decodeURIComponent(urlPath).replace(/^\/+/, "");
  if (p.endsWith("/")) p = p.slice(0, -1);
  const candidates = p === "" ? ["index.html"] : [p, `${p}.html`, `${p}/index.html`];
  for (const c of candidates) if (fileSet.has(c)) return c;
  const target = redirects.get(`/${p}`);
  if (target && hops < 3) return resolve(target, hops + 1);
  return null;
}

const idCache = new Map();
function idsOf(file) {
  if (!idCache.has(file)) {
    const html = fs.readFileSync(path.join(root, file), "utf8");
    idCache.set(file, new Set([...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1])));
  }
  return idCache.get(file);
}

const decode = (s) => s.replace(/&amp;/g, "&").replace(/&#x27;/g, "'").replace(/&quot;/g, '"');

/** Normalise a link to a same-site path + fragment, or null if it's external. */
function internal(raw, base) {
  const href = decode(raw.trim());
  if (!href || /^(mailto:|tel:|javascript:|data:|blob:|sms:)/i.test(href)) return null;
  let u;
  try {
    u = new URL(href, `${ORIGIN}${base}`);
  } catch {
    return { broken: `unparseable URL "${href}"` };
  }
  if (u.origin !== ORIGIN) return null;
  return { path: u.pathname, hash: u.hash.slice(1) };
}

const broken = [];
let checked = 0;

function check(sourceLabel, sourceFile, raw, base) {
  const link = internal(raw, base);
  if (!link) return;
  checked++;
  if (link.broken) return broken.push(`${sourceLabel}: ${link.broken}`);
  if (DYNAMIC.some((r) => r.test(link.path))) return;
  if (/^\/admin(\/|$)/.test(link.path)) return;
  const target = link.path === base && sourceFile ? sourceFile : resolve(link.path);
  if (!target) return broken.push(`${sourceLabel}: ${raw} → no page or file at ${link.path}`);
  if (link.hash && target.endsWith(".html") && !idsOf(target).has(decodeURIComponent(link.hash)))
    broken.push(`${sourceLabel}: ${raw} → ${target} has no id="${link.hash}"`);
}

for (const file of files.filter((f) => f.endsWith(".html"))) {
  const rel = path.relative(root, file).split(path.sep).join("/");
  if (rel.startsWith("admin") || rel === "temp_gallery.html") continue;
  const html = fs.readFileSync(file, "utf8")
    // Inline scripts and JSON-LD aren't navigable links.
    .replace(/<script[\s\S]*?<\/script>/g, "");
  const urlPath = "/" + rel.replace(/(?:^|\/)index\.html$/, "").replace(/\.html$/, "");
  for (const m of html.matchAll(/<(?:a|link|img|source|video|audio|iframe)\b[^>]*?\s(?:href|src)="([^"]*)"/g)) {
    // rel="preconnect"/"dns-prefetch" point at origins, not pages.
    if (/rel="(?:preconnect|dns-prefetch)"/.test(m[0])) continue;
    check(rel, rel, m[1], urlPath);
  }
  for (const m of html.matchAll(/\ssrcset="([^"]*)"/g))
    for (const part of m[1].split(",")) check(rel, rel, part.trim().split(/\s+/)[0], urlPath);
}

if (withContent) {
  const contentRoot = path.resolve("content");
  for (const file of fs.existsSync(contentRoot) ? walk(contentRoot).filter((f) => f.endsWith(".md")) : []) {
    const rel = path.relative(process.cwd(), file).split(path.sep).join("/");
    const md = fs.readFileSync(file, "utf8").replace(/```[\s\S]*?```/g, "");
    for (const m of md.matchAll(/\]\((\/[^)\s]*)(?:\s+"[^"]*")?\)|(?:href|src)="(\/[^"]*)"/g)) check(rel, null, m[1] ?? m[2], "/");
  }
}

// The sitemap must list only pages that exist.
const sitemap = path.join(root, "sitemap.xml");
if (fs.existsSync(sitemap)) {
  for (const m of fs.readFileSync(sitemap, "utf8").matchAll(/<(?:loc|image:loc)>([^<]+)<\/(?:loc|image:loc)>/g)) check("sitemap.xml", null, m[1], "/");
}

if (broken.length) {
  console.error(`✗ ${broken.length} broken internal link(s) out of ${checked} checked:\n`);
  for (const b of [...new Set(broken)]) console.error(`  ${b}`);
  process.exit(1);
}
console.log(`✓ ${checked} internal links checked, none broken.`);
