import { writeFile, readFile } from "node:fs/promises";
const target = new URL("../cms/font-catalog.ts", import.meta.url);
async function json(url) {
  const r = await fetch(url, { signal: AbortSignal.timeout(20000) });
  if (!r.ok) throw new Error(`Font catalog returned ${r.status}`);
  return JSON.parse((await r.text()).replace(/^\)\]\}'\s*/, ""));
}
try {
  const google = await json("https://fonts.google.com/metadata/fonts");
  const share = await json("https://api.fontshare.com/v2/fonts");
  const valid = (s) => typeof s === "string" && /^[\w -]{2,60}$/.test(s);
  const data = {
    updatedAt: new Date().toISOString(),
    google: [
      ...new Set(google.familyMetadataList.map((f) => f.family).filter(valid)),
    ].sort(),
    fontshare: [
      ...new Set(
        (Array.isArray(share) ? share : (share.fonts ?? share.data))
          .map((f) => f.name ?? f.family)
          .filter(valid),
      ),
    ].sort(),
  };
  if (data.google.length < 1000 || data.fontshare.length < 20)
    throw new Error("Unexpected font catalog shape");
  await writeFile(
    target,
    "// Generated by npm run fonts:sync.\nexport default " +
      JSON.stringify(data, null, 2) +
      ";\n",
  );
  console.log(
    `Font catalog: ${data.google.length} Google Fonts, ${data.fontshare.length} Fontshare families`,
  );
} catch (e) {
  try {
    await readFile(target);
    console.warn(`Keeping last verified font catalog: ${e.message}`);
  } catch {
    throw e;
  }
}
